# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-north-1
          role-to-assume: arn:aws:iam::920373027332:role/GithubActionsRole
      - uses: hashicorp/setup-terraform@v3 
      - run: terraform fmt -check

  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-north-1
          role-to-assume: arn:aws:iam::920373027332:role/GithubActionsRole
      - uses: hashicorp/setup-terraform@v3 
      - uses: actions/checkout@v4.2.0
      - run: terraform plan -input=false

  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-north-1
          role-to-assume: arn:aws:iam::920373027332:role/GithubActionsRole
      - uses: hashicorp/setup-terraform@v3 
       - uses: actions/checkout@v4.2.0
      - run: terraform apply -auto-approve -input=false
